# Pre-Season {-}

## The year of the Manager {-}

With English clubs again failing to mount a serious challenge in the European Champions league and the abject failure of the England team at the European championships, it was little wonder that much of the focus was on the manager merry-go-round as some of the elite managers tussled for the title

Each top club had their own manager sub-plot

 * Pep Guardiola (Manchester City) - would his first foray into English football get Man City a title and  a final appearance in the Champion's league or would he be found out by the consistently tougher competition he would face
 compared with his terms at Barcelona and Bayern Munich
 
 * Jose Mourinho (Manchester United) - could he bounce back from the humiliation of his previous season at Chelsea and, with the help of a big transfer chest,
 return the team to its 'tradition' of glamourous winning football and young player development
 
 * Arsene Wenger (Arsenal) - would his relatively tight-fisted approach (backed by his board) and apparant obsession with  buying midfielders
  just emphasize that the previous campaign was his last best chance to capture another title
  
* Mauricio Poccetino (Tottenham Hotspur) -  Could the development of young stars like Kane & Alli which had endeared him to the media continue or would the Champions League prove too big a burden for a club where player wages in comparison to those at other clubs might become an issue

* Jurgen Klopp (Liverpool) - Could the exciting brand of football he introduced in his first part-season be maintained more consistently and the obvious defensive weaknesses (I'm looking at you Mignolet and Moreno) be overcome

 * Antonio Conte (Chelsea) - Would the volatile Italian translate his success at both Juventus and international level to Chelsea team that had under-performed in almost every possition. An improvement in the ageing defence looked unlikely but a bounce back from players like Costa and, in particular, Hazard would be essential
  

